---
title: "HW1"
author: "Kerin Grewal"
date: "Jan 21st"
output: pdf_document
---


##1. Create the vecors:
###(a) (1, 2, 3, . . . , 19, 20)

```
##  [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20
```

###(b) (20, 19, . . . , 2, 1)
```{r echo= FALSE}
y <- seq(20, 1, -1)
y
```

###(c) (1, 2, 3, . . . , 19, 20, 19, 18, . . . , 2, 1)
```{r echo= FALSE}
c(1:20, 19:1)
```

###(d) (4, 6, 3) and assign it to the name tmp.
```{r echo= FALSE}
tmp <- c(4, 6, 3)
tmp
```

###(e) (4, 6, 3, 4, 6, 3, . . . , 4, 6, 3) where there are 10 occurrences of 4.
```{r echo= FALSE}
b <- rep(tmp, 10)
b
```

###(f) (4, 6, 3, 4, 6, 3, . . . , 4, 6, 3, 4) where there are 11 occurrences of 4, 10 occurrences of 6 and 10 occurrences of 3.
```{r echo= FALSE}
a <- rep(tmp, length = 31)
a
```

###(g) (4, 4, . . . , 4, 6, 6, . . . , 6, 3, 3, . . . , 3) where there are 10 occurrences of 4, 20 occurrences of 6 and 30 occurrences of 3.
```{r echo= FALSE}
c = c(rep(4, 10), rep(6, 20), rep(3, 30))
c
```

##2. Create a vector of the values of e^x cos(x) at x = 3, 3.1, 3.2, . . . , 6.
```{r echo= FALSE}
x <- seq(3, 6, by = 0.1)
vect <- exp(x) * cos(x)
vect
```

